/*
 * Master script for loading Patient360 data
 * Includes: CSV data, images, and PDFs
 */

-- Step 1: Load CSV data into tables
-- Execute load_csv_data.sql first

-- Step 2: Create stages and upload files
-- Then execute load_files.sql

-- Step 3: Verify data loads
USE DATABASE PATIENT360;
USE SCHEMA RAW;

SELECT 'DOCTORS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DOCTORS
UNION ALL SELECT 'PATIENTS', COUNT(*) FROM PATIENTS
UNION ALL SELECT 'VISITS', COUNT(*) FROM VISITS
UNION ALL SELECT 'LAB_RESULTS', COUNT(*) FROM LAB_RESULTS
UNION ALL SELECT 'DIAGNOSTIC_REPORTS', COUNT(*) FROM DIAGNOSTIC_REPORTS
UNION ALL SELECT 'PRESCRIPTIONS', COUNT(*) FROM PRESCRIPTIONS
UNION ALL SELECT 'CLINICAL_NOTES', COUNT(*) FROM CLINICAL_NOTES
UNION ALL SELECT 'INSURANCE_CLAIMS', COUNT(*) FROM INSURANCE_CLAIMS
UNION ALL SELECT 'DIAGNOSTIC_CENTERS', COUNT(*) FROM DIAGNOSTIC_CENTERS;